// Package store_test verifies the data-access foundation against real Postgres.
//
// A mock cannot produce a real 23P01, so nothing here is mocked. The whole point
// of these tests is that the errors are generated by the actual schema.
package store_test

import (
	"context"
	"errors"
	"testing"

	"github.com/google/uuid"
	"github.com/iitg-playhack/sportsbook/internal/store"
	"github.com/iitg-playhack/sportsbook/test/testutil"
	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/require"
)

// insertBooking is a plain INSERT with no preceding SELECT — the read-then-write
// gap is the bug the schema exists to remove.
const insertBooking = `
INSERT INTO bookings (facility_id, user_id, is_exclusive, during, status, idem_key)
VALUES ($1, $2, $3, tstzrange($4::timestamptz, $5::timestamptz, '[)'), 'CONFIRMED', $6)
RETURNING id`

func countBookings(t *testing.T, pg *testutil.PG, facility uuid.UUID) int {
	t.Helper()
	var n int
	require.NoError(t, pg.Pool.QueryRow(context.Background(),
		`SELECT count(*) FROM bookings WHERE facility_id = $1`, facility).Scan(&n))
	return n
}

func TestWithTx_CommitsOnSuccess(t *testing.T) {
	pg := testutil.Postgres(t)
	ctx := context.Background()

	court := testutil.CourtID()
	user := testutil.StudentID(0)
	start, end := testutil.Slot18()

	err := store.WithTx(ctx, pg.Pool, func(tx pgx.Tx) error {
		var id uuid.UUID
		return tx.QueryRow(ctx, insertBooking, court, user, true, start, end, nil).Scan(&id)
	})
	require.NoError(t, err)

	require.Equal(t, 1, countBookings(t, pg, court), "a committed transaction must leave its row")
}

func TestWithTx_RollsBackOnError(t *testing.T) {
	pg := testutil.Postgres(t)
	ctx := context.Background()

	court := testutil.CourtID()
	user := testutil.StudentID(0)
	start, end := testutil.Slot18()

	sentinel := errors.New("business rule said no")

	err := store.WithTx(ctx, pg.Pool, func(tx pgx.Tx) error {
		var id uuid.UUID
		if err := tx.QueryRow(ctx, insertBooking, court, user, true, start, end, nil).Scan(&id); err != nil {
			return err
		}
		// The row exists inside the transaction...
		var n int
		if err := tx.QueryRow(ctx, `SELECT count(*) FROM bookings WHERE facility_id = $1`, court).Scan(&n); err != nil {
			return err
		}
		require.Equal(t, 1, n, "the insert must be visible inside its own transaction")

		return sentinel
	})

	// ...and the caller's error is returned unwrapped, not swallowed or replaced.
	require.ErrorIs(t, err, sentinel)
	require.Equal(t, 0, countBookings(t, pg, court), "a failed transaction must leave nothing behind")
}

func TestWithTx_RollsBackOnPanic(t *testing.T) {
	pg := testutil.Postgres(t)
	ctx := context.Background()

	court := testutil.CourtID()
	user := testutil.StudentID(0)
	start, end := testutil.Slot18()

	// The panic must reach the caller. Swallowing it would turn a bug into a
	// silent no-op, which is far worse than a crash.
	require.PanicsWithValue(t, "boom", func() {
		_ = store.WithTx(ctx, pg.Pool, func(tx pgx.Tx) error {
			var id uuid.UUID
			if err := tx.QueryRow(ctx, insertBooking, court, user, true, start, end, nil).Scan(&id); err != nil {
				return err
			}
			panic("boom")
		})
	})

	require.Equal(t, 0, countBookings(t, pg, court), "a panicking transaction must roll back")

	// And the pool must still be usable — a leaked connection stuck in an
	// aborted transaction would poison every later request.
	require.NoError(t, pg.Pool.Ping(ctx))

	err := store.WithTx(ctx, pg.Pool, func(tx pgx.Tx) error {
		var id uuid.UUID
		return tx.QueryRow(ctx, insertBooking, court, user, true, start, end, nil).Scan(&id)
	})
	require.NoError(t, err, "the pool must still work after a panic rollback")
	require.Equal(t, 1, countBookings(t, pg, court))
}
